#!/usr/bin/python3
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024 Bardia Moshiri <fakeshell@bardia.tech>

import sys
import dbus

bus = dbus.SessionBus()

manager = dbus.Interface(bus.get_object('org.ofono.mms', '/org/ofono/mms'),
                         'org.ofono.mms.Manager')

services = manager.GetServices()
path = services[0][0]

service = dbus.Interface(bus.get_object('org.ofono.mms', path),
                         'org.ofono.mms.Service')

if len(sys.argv) > 1:
    allowed = dbus.Boolean(int(sys.argv[1]))
else:
    allowed = dbus.Boolean(1)

print("Setting delivery report use for {}...(UseDeliveryReports={})".format(path, int(allowed)))

service.SetProperty("UseDeliveryReports", allowed)
